name: semgrep

permissions: read-all

on:
  pull_request:
    branches: [main, master]
  workflow_dispatch:

concurrency:
  group: semgrep-${{ github.ref }}
  cancel-in-progress: true

jobs:
  scan:
    runs-on: ubuntu-latest
    if: github.actor != 'dependabot[bot]'
    container:
      image: semgrep/semgrep
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Semgrep scan
        run: |
          semgrep scan --config auto --error
